version: '3'
services:
  cadot-info-like:
    image: cadotinfo/symfony5
    container_name: cadot-info-like
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80
 
networks:
  web:
    external: true
